# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright René Ferdinand Rivera Morell.
# Copyright 2020 Jayesh Vinay Badwaik

trigger:
  branches:
    include:
      - develop
      - release
      - feature/*
      - pr/*
      - issue/*
  paths:
    exclude:
      - .circleci/*
      - .drone.star
      - .github/workflows/*
      - .semaphore/*
      - .travis.yml
      - appveyor.yml
pr:
  branches:
    include:
      - develop
schedules:
  - cron: "0 1 * * 0"
    displayName: "Weekly"
    branches:
      include:
        - develop

stages:
  - template: ".ci/azp.yml"
    parameters:
      name: Core
      depends_on: []
      toolsets:
        - "gcc-16"
        - "clang-23"
        - "clang-darwin-26.0"
        - "msvc-14.5"
      b2_tests:
        - name: "Warnings"
          dir: tests
          args: "-a variant=pedantic"

  - template: ".ci/azp.yml"
    parameters:
      name: Sanitize
      depends_on: []
      toolsets:
        - "gcc-16"
      b2_tests:
        - name: "Address"
          dir: tests
          args: "-a address-sanitizer=on variant=debug"
        - name: "Undefined"
          dir: tests
          args: "-a undefined-sanitizer=on variant=debug"

  - template: ".ci/azp.yml"
    parameters:
      name: Compilers
      depends_on: ["Core", "Sanitize"]
      b2_tests:
        - name: "B2 Test"
          dir: tests
          args: "--debug-configuration -a variant=debug,release"
      cmake_tests:
        - name: "Cmake Install"
          args: "-DCMAKE_CXX_STANDARD=11"
          dir: cmake_d
          make_args: "install"
        - name: "Cmake Test"
          args: "-DCMAKE_CXX_STANDARD=11"
          dir: cmake_d
          cml_dir: tests/lib_use_test
