= Lyra
:copyright: Copyright 2019 Rene Rivera
:author: Rene Rivera
:email: grafikrobot@gmail.com
:version-label!:
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:sectnumlevels: 5
:icons: font
:source-highlighter: pygments
:source-language: cpp
:toc: left
:toclevels: 5
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:CPP: C++
:PP: ++
:P: +

ifdef::backend-html5[]
++++
<style>
include::std.css[]
</style>
++++
endif::[]

== Introduction

Lyra is a simple to use, composing, command line parser for C++ 11 and beyond.
It provides easy to use command line parsing for most use cases with a minimal
source footprint. It doesn't aim to provide all features for all users.

=== License

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

=== Features

* Header only with no external dependencies (except the std library).
* Define your interface once to get parsing, type conversions and usage
  strings with no redundancy.
* Composing. Each `Opt` or `Arg` is an independent parser. Combine these to
  produce a composite parser - this can be done in stages across multiple
  function calls -- or even projects.
* Bind parsers directly to variables that will receive the results of the parse
  -- no intermediate dictionaries to worry about.
* Or can also bind parsers to lambdas for more custom handling.
* Deduces types from bound variables or lambdas and performs type conversions
  (via `ostream <<`), with error handling, behind the scenes.
* Bind parsers to vectors for args that can have multiple values.
* Uses Result types for error propagation, rather than exceptions (doesn't yet
  build with exceptions disabled, but that will be coming later)
* Models POSIX standards for short and long opt behavior.
* Customizable option syntax.
* Specify cardinality of `Arg`-s from one to many.

== Usage

To use, include the header with `#include "lyra/lyra.hpp"`.

=== Single Option

A parser for a single option can be created like this:

[source,c++]
----
include::../examples/doc_example1.cpp[tag=part1]
----

You can use this parser by giving it the program arguments of `main`:

[source,c++]
----
include::../examples/doc_example1.cpp[tag=part2]
----

Which could be used as:

[source,shell]
----
> example1 -w 10
width = 10
----

=== Multiple Options

It's rare that we are interested in accepting a single option. To parse
multiple options we compose the options as alternatives with the *or*
operator (`|`).

[source,c++]
----
include::../examples/doc_example2.cpp[tag=part1]
----

You can use this parser by giving it the program arguments of `main`:

[source,c++]
----
include::../examples/doc_example2.cpp[tag=part2]
----

Which could be used as:

[source,shell]
----
> example2 -w 10 --name=Lyra
width = 10, name = Lyra, doIt = 0
----

== Help Option

From the specified arguments parser we also get convenient help output.
In addition to specifying the

[source,c++]
----
include::../examples/doc_example3.cpp[tag=part1]
----
<1> Flag variable to indicate if we get the `-h` or `--help` option.
<2> The help specific option parser.

We need some changes when using the parser to check if the help option was
specified:

[source,c++]
----
include::../examples/doc_example3.cpp[tag=part2]
----
<1> We print out the help text on error.
<2> And we also print it out when specified.

== Reference

:leveloffset: +2

include::../include/lyra/cli_parser.hpp[tag=reference]

include::../include/lyra/opt.hpp[tag=reference]

include::../include/lyra/arg.hpp[tag=reference]

include::../include/lyra/help.hpp[tag=reference]

include::../include/lyra/exe_name.hpp[tag=reference]

include::../include/lyra/args.hpp[tag=reference]

:leveloffset: -2

== History

=== 1.0

This is the initial base version based on Clara library. Changes from that
library:

* Documentation.
* Zero dependencies, even internally, by removing TextFlow and Catch bundled
  libraries.
* Conform to Pitchfork Layout R1.
* Tested with Visual Studio 2015, VS 2017, MinGW (gcc 5.3), MinGW-64 (gcc 6.3,
  7.3, 8.1), Linux (clang 3.5, 3.8, 3.9, 4, 5; gcc 4.8, 4.9, 5, 6, 7, 8),
  Xcode (8.3, 9, 9.1, 10.1).
* Tested with C++ 11, 14, 17, and 2a.
* *New*: customization of option prefix and separators.
* *New*: support for repeated arguments, from one to many.
